### PR TITLE
fix: show active page highlight in navbar

### LINKED ISSUE #674: Highlight Active Page in Navbar
### What is this issue related to?

Enhancement

### Description

Currently, the navigation bar does not highlight the active page, making it difficult for users to know which page they are on. We need to add functionality that will visually highlight the active page in the Navbar, improving navigation and user experience.

### Steps to Reproduce:

- Go to the website's homepage.
- Click on any of the navbar links (e.g., Home, Pricing, About).
- Notice that the active page is not visually indicated.

### Current Behaviour

Image

### Expected Behavior:

The current page in the Navbar should be visually highlighted, such as with a different background color or text style, to clearly indicate which page the user is on.

### Why should this enhancement be implemented? Add additional informaiton.

- Improved UX: Users can easily identify their current page.
- Accessibility: Clear active state helps users with visual impairments.
- Consistency: Aligns with common design patterns across modern websites.

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by Ravisukhwal76**
## Summary
This PR adds functionality to visually highlight the active page in the navigation bar, improving user orientation and navigation experience.

closes #674 

## Description

- Applied conditional logic to assign an active class to the current page link in the navbar.
- Updated CSS styles for the active class to clearly distinguish the active link.
- Verified that highlighting works correctly across all primary routes.

## Video
https://github.com/user-attachments/assets/a8264e06-ee7d-4f59-9e0c-0055fa7bbbd4

## What type of PR is this? (Check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📄 Documentation Update
- [ ] 👨‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] ✅ Test
- [ ] 🛠️ CI/CD

## Checklist
- [x] I have performed a self-review of my code  
- [ ] I have commented my code, particularly in hard-to-understand areas  
- [ ] I have added tests that prove my fix is effective or that my feature works  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ui/src/components/header/MobileHeaderMenu.jsx [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { useEffect, useContext } from "react";
+import { useEffect, useContext, useState, useLocation } from "react";
```
Comment (tanwarAalok) [inline packages/ui/src/components/header/MobileHeaderMenu.jsx]: useLocation is incorrectly imported , it should be from react-router-dom

**Review by aps08 — CHANGES_REQUESTED** [review]
video needed.

File: packages/ui/src/components/header/MobileHeaderMenu.jsx (hunk 1 above)
Comment (Ravisukhwal76) [reply packages/ui/src/components/header/MobileHeaderMenu.jsx]: Thanks for pointing that out. I've corrected the import—useLocation is now properly imported from react-router-dom.

**Review by shafat730 — COMMENTED** [review]
Add Screenshot of the test coverage

**Comment by Ravisukhwal76** [comment]
> Add Screenshot of the test coverage

image

**Comment by Ravisukhwal76** [comment]
> video needed.

Video added

**Comment by aps08** [comment]
@Ravisukhwal76 why the issue is closed ?

**Comment by Ravisukhwal76** [comment]
> @Ravisukhwal76 why the issue is closed ?

I have reoped the issue.
