### PR TITLE
713 Refactor constants fix lint issues & clean unused codeassets

### LINKED ISSUE #713: Refactor constants, fix lint issues, and clean up unused code/assets
### Describe the enhancement

This task is about cleaning up the codebase by:

- Moving repeated values (constants) into one shared constants file
- Fixing small lint issues in a few components
- Removing unused images & unneccessary comments
- Making use of useApi hook & spinner component to make UI more consistent

### Why should this enhancement be implemented? Add additional informaiton.

Cleaning up the code will make it easier to work with, more organized, and consistent across the app. It also helps reduce clutter by removing unused code and assets. Below are the areas that need updates:

- `/components/usage` – move constants to a shared constants file
- `/components/header` – fix useMemo lint issues in Header & MobileHeader
- `/components/demo` – use useApi hook, remove old loading section, use existing spinner
- `/components/currentplan` – move static text to shared constants file
- `/components/changepassword` – move constants to shared constants file
- `/components/catalog/Catalog` – remove single-line comments
- `/components/apikeyform` – move constants to shared constants file
- `/assets` – delete images that aren’t used
- `/utils` – remove unused constants

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by theboyofdream**
## Description
Issue Link: [713](https://github.com/TeamShiksha/openlogo/issues/713)

`/components/usage` - contstant to be moved into constant file. 
`/components/header` - both header and mobile header have some linting issues while using usememo. 
`/components/currentplan` - move text to contstant file. 
`/components/changepassword` - move constant to constant file. 
`/components/catalog/Catalog` - remove single line comments. 
`/components/apikeyform` - move constant to constant file. 
`/components/demo` - should use the useAPi hook. Removed loading section. 
`/assets` - remove images not in use.
`/utils` - remove constants not in use.
`/components/analytics/analytics` - removed infinite loop of useEffect
`/components/analytics/analyticscard` - removed infinite loop of useEffect & un-necessary useStates.
`/components/auth/signin` - added loading attribute on submit button

## What type of PR is this? (Check all applicable)

- [x] 👨‍💻 Code Refactor
- [x] ✅ Test

## Screenshots (if applicable)

image

https://github.com/user-attachments/assets/06989634-631c-4fd8-9b2d-aa07b5aeb15f

## Checklist
- [x] I have performed a self-review of my code  
- [x] I have commented my code, particularly in hard-to-understand areas  
- [x] I have added tests that prove my fix is effective or that my feature works  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ui/src/components/analytics/AnalyticsCard.jsx [hunk 1]
```diff
@@ -1,23 +1,23 @@
...
+  const fetchAndUpdatePercentageChange = useCallback(async () => {
     setChange(api);
-  }
+  }, [api, setChange]);
 
   useEffect(() => {
     fetchAndUpdateValue();
     fetchAndUpdatePercentageChange(api);
-  }, [api]);
+  }, [api, fetchAndUpdateValue, fetchAndUpdatePercentageChange]);
```
Comment (aps08) [inline packages/ui/src/components/analytics/AnalyticsCard.jsx]: Have you  tested it ? Isn't this going to run the useeffect infinitely. ?

**Review by aps08 — COMMENTED** [review]
Questions.

File: packages/ui/src/components/analytics/AnalyticsCard.jsx (hunk 1 above)
Comment (theboyofdream) [reply packages/ui/src/components/analytics/AnalyticsCard.jsx]: Yes it will run infinitely. I will fix this & also update the test-case if needed

**Review by aps08 — APPROVED** [review]
