### PR TITLE
Fixed Responsive header(UI): nav-links not showing at 1024px breakpoint

### LINKED ISSUE #820: `v0.3.0` Responsive header nav not showing at 1024px breakpoint
### Describe your issue

When the window width is exactly 1024px, the navigation links in the header disappear. The nav is not showing as mobile view nor desktop view.

### Steps to reproduce

1) Open the application page with the header.

2) Resize the browser window to exactly 1024px width (Laptop breakpoint).

3) Observe that the navigation links disappear — neither mobile nor desktop view is displayed.

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by parshant0717**
## Description
Fixed #820.

This PR resolves a UI bug in the Header component and header.module.css file. At the exact screen size of 1024px, the navigation links were not displaying correctly — they did not appear in either the mobile view (collapsed menu) or the desktop view (inline links).

The fix ensures that the nav links render properly at the 1024px breakpoint, maintaining consistency between mobile and desktop views.

## What type of PR is this? (Check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📄 Documentation Update
- [x] 👨‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🛠️ CI/CD

### Before

https://github.com/user-attachments/assets/89069b60-b7ee-41ce-bf33-fa2a15b82b4a

### After

https://github.com/user-attachments/assets/94374e19-7647-4a5d-b7b8-bef03e565d91

### Test Coverage

Screenshot (308)

## Checklist
- [x] I have performed a self-review of my code  
- [ ] I have commented my code, particularly in hard-to-understand areas  
- [ ] I have added tests that prove my fix is effective or that my feature works  
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by TanishqSingla** [comment]
Hard to review the changes from photos, please share video if possible

File: packages/ui/src/components/header/Header.jsx [hunk 1]
```diff
@@ -67,38 +67,45 @@ const Header = ({ openAuthModal }) => {
...
           <span className={styles["brand-name"]}>{BRANDING.brandName}</span>
         </button>
-        <div className={styles["nav-bar"]}>
-          {NAVBAR_ITEMS.map((item) => {
-            const [itemPath, itemSection] = item.url.split("#");
-            const isActive =
-              item.type === "route"
-                ? currentPath === item.url
-                : currentPath === itemPath && activeSection === itemSection;
+        {!isMobile && (
```
Comment (TanishqSingla) [inline packages/ui/src/components/header/Header.jsx]: We are hiding the navbar in js and in css using `display: none`? Am I getting this right? If yes why such a redundant approach?

**Review by TanishqSingla — CHANGES_REQUESTED** [review]

File: packages/ui/src/components/header/Header.jsx (hunk 1 above)
Comment (parshant0717) [reply packages/ui/src/components/header/Header.jsx]: actually css was overriding but got the solution doing requested changes.

**Review by TanishqSingla — APPROVED** [review]

**Review by theboyofdream — APPROVED** [review]
