### PR TITLE
fix: catalog logo upload fix in backend

### LINKED ISSUE #754: Integrate the catalog backend api
### Describe the enhancement

- In PR #738 , all the catalog features are integrated in the backend
- raise a new PR for backend only that includes the changes in PR #738 
- PR should also include test files

### Why should this enhancement be implemented? Add additional informaiton.

_No response_

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by Aniketvish0**
## Description
closes #754

Refactored the code related to catalog image upload in backend 

- Introduced regex to filter out company names from company url
- Added test for add logo and update logo 

## What type of PR is this? (Check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📄 Documentation Update
- [x] 👨‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] ✅ Test
- [ ] 🛠️ CI/CD

## Screenshots - All catlog api's working as expected
image
Screenshot from 2025-07-23 17-22-26
Screenshot from 2025-07-23 17-26-56

### Test Passed:
image

## Checklist
- [x] I have performed a self-review of my code  
- [x] I have commented my code, particularly in hard-to-understand areas  
- [x] I have added tests that prove my fix is effective or that my feature works  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/app/utils/constants.js [hunk 1]
```diff
@@ -87,8 +88,11 @@ const Messages = {
   COMPANY_URL_ALREADY_PENDING: "This company url is already under review.",
 };
 
+const ExtractCompanyNameFromUrlRegex = /:\/\/(?:www\.)?([^./]+)\./i;
```
Comment (TanishqSingla) [inline packages/app/utils/constants.js:91]: Does this regex handle sub-domain as well? Like gemini.google.com, or we are expecting that we're not going to receive that input

File: packages/app/services/images.js [hunk 2]
```diff
@@ -101,21 +112,49 @@ class ImageServices {
     };
   }
 
+  /**
+   * Updates an image document by its unique identifier.
+   *
+   * @async
+   * @param {string} id - The unique identifier of the image to update.
+   * @param {Object} updateObj - The fields and values to update in the image document.
+   * @returns {Promise<Object>} The updated image document.
```
Comment (TanishqSingla) [inline packages/app/services/images.js]: Remove the type here, since your function clearly returns an object this will infer the type as any

File: packages/app/services/images.js [hunk 3]
```diff
@@ -101,21 +112,49 @@ class ImageServices {
...
-  async getImagesByUserId(userId) {
-    return await this.imageRepository.getAllImageByUserId(userId);
+  /**
+   * Retrieves a paginated list of images for a specific user.
+   *
+   * @async
+   * @param {string} userId - The unique identifier of the user whose images are to be retrieved.
+   * @param {number} skip - The number of images to skip (for pagination).
+   * @param {number} limit - The maximum number of images to return.
+   * @returns {Promise<Array<Object>>} A promise that resolves to an array of image documents.
```
Comment (TanishqSingla) [inline packages/app/services/images.js]: same as above

**Review by TanishqSingla — CHANGES_REQUESTED** [review]

File: packages/app/utils/constants.js (hunk 1 above)
Comment (Aniketvish0) [reply packages/app/utils/constants.js:91]: This only handles the main domain for now, we are not expecting subdomain here.
- might be changed in updates

File: packages/app/services/images.js (hunk 2 above)
Comment (Aniketvish0) [reply packages/app/services/images.js]: okay

File: packages/app/services/images.js (hunk 3 above)
Comment (Aniketvish0) [reply packages/app/services/images.js]: updated

File: packages/app/utils/constants.js (hunk 1 above)
Comment (TanishqSingla) [reply packages/app/utils/constants.js:91]: cool

**Review by TanishqSingla — APPROVED** [review]

File: packages/app/services/images.js [hunk 4]
```diff
@@ -55,30 +57,39 @@ class ImageServices {
...
-        company.company_name,
-        undefined,
-        false
-      );
-      if (!signedUrl) continue;
-      dataList.push({
-        companyName: company.company_name.split(".")[0],
-        image: signedUrl,
-      });
+    const results = await Promise.allSettled(
```
Comment (aps08) [inline packages/app/services/images.js:60]: what is happening here ?

**Review by aps08 — CHANGES_REQUESTED** [review]
No video or screenshot to show working of the changes.

File: packages/app/services/images.js (hunk 4 above)
Comment (Aniketvish0) [reply packages/app/services/images.js:60]: results receives an array of object for reach promise is full filled or rejected 

then we are pushing the data to datalist on the basis of whether promise is fulfilled or not

**Comment by Aniketvish0** [comment]
added the proof of working in description
