### PR TITLE
UI fixes on frontend (font sizes, drop down misalignment)

### LINKED ISSUE #728: UI style fixes
### Describe the enhancement

Currently there are inconsistencies in our UI, these include border styles, font and overall layout.

- [ ] Dropdown is misaligned
<details>
<summary>Click to expand</summary>
Image
</details>

- [ ] Inconsistent font sizes and color
<details>
<summary>Click to expand</summary>

Image

</details>

- [ ] Add loading spinner instead of text
<details>
<summary>Click to expand</summary>

Image

</details>

### Why should this enhancement be implemented? Add additional informaiton.

To provide a consistent user experience to the user 

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by Idontnol**
## Description
#728 

- Unified font sizes for headings, paragraphs across dashboard page for consistency 
- Updated dropdown configurations:
  - Ensured full-width dropdowns on mobile.
  - Matched inner padding, text colors across both dropdowns.
  - Added a new arrow icon and adjusted its alignment slightly to the left for better balance.
- Replaced native select with custom Dropdown component and refactored it to accept a className prop.
- Regarding loading spinner Arya is working on it. He has raised a PR already.
- Replaced loading.. text in ProtectedRoute with loading spinner

## What type of PR is this? (Check all applicable)

- [x] 👨‍💻 Code Refactor
- [x] 🔥 UI Improvements

## Screenshots (if applicable)

https://github.com/user-attachments/assets/defbe8a6-2f72-430b-b896-2f385f22f789

## Checklist
- [x] I have performed a self-review of my code  
- [x] I have commented my code, particularly in hard-to-understand areas  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ui/src/utils/ProtectedRoute.jsx [hunk 1]
```diff
@@ -36,7 +37,19 @@ function ProtectedRoute({ adminOnly = false, children }) {
   }
 
   if (loading) {
-    return <div>Loading...</div>;
+    return (
+      <div
+        style={{
```
Comment (TanishqSingla) [inline packages/ui/src/utils/ProtectedRoute.jsx:42]: is there any reason for inline class here?

File: packages/ui/src/components/usage/Usage.module.css [hunk 2]
```diff
@@ -40,3 +40,10 @@
   display: flex;
   justify-content: center;
 }
+
+@media (min-width: 768px) and (max-width: 1300px) {
+  .usage-statistics {
+    display: flex;
+    gap: 1.3rem;
```
Comment (TanishqSingla) [inline packages/ui/src/components/usage/Usage.module.css]: is `1.3rem` standardized?

**Review by TanishqSingla — CHANGES_REQUESTED** [review]

File: packages/ui/src/utils/ProtectedRoute.jsx (hunk 1 above)
Comment (Idontnol) [reply packages/ui/src/utils/ProtectedRoute.jsx:42]: I have used inline style here because protected route doesn't have dedicated CSS file I have mentioned this in last meeting.

File: packages/ui/src/components/usage/Usage.module.css (hunk 2 above)
Comment (Idontnol) [reply packages/ui/src/components/usage/Usage.module.css]: I used it to get visually balanced spacing between items.

**Review by TanishqSingla — APPROVED** [review]

**Review by aps08 — APPROVED** [review]
