### PR TITLE
fix: frontend inconsistecies from #815

### LINKED ISSUE #815: UI Issues: Missing Loading Spinners, Duplicate Errors, Form Validation Bug, Docs Language Not Syncing
### Describe your issue

Part 01: UI issues found during testing of stage.openlogo.fyi

1. Loading spinner not implemented in SignIn form, Forgot Password form, Respond/Reject message form, Get in touch form.
When submitting these forms `SignIn`, `Forgot Password`, `Respond message`, `Reject mess` & `Get in touch`. Button get's disabled but not showing loading spinner.

Image

2. In SignIn modal error we get text message & toast messageWhen wrong credentials entered in SignIn form we get text message & toast message both. Only toast message should have been shown.

Image

 
3. User Info form shows error text above `username` input fieldInside the User Dashboard - UserInfo card we get errors above & below `username` input field.

Image

4. In docs page change language in one API doesn't change language for another API.
In Docs page expected to change code language throughout whole code block

### Steps to reproduce

Loading Spinner  & Error text message 
1. Click on Get Started button
2. Fill form with wrong credentials
3. Submit the form

After logging in, go to Dashboard
1. In user info form enter name with special characters
2. Submit

Docs
1. Go to docs page
2. Change coding language of `Logo Retreival` code snippet to python
3. Scroll down to `Search` code snippet

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by Aniketvish0**
## Description
fixes #815 

Fixed the following frontend inconsistencies 
- Implemented Loading spinner in SignIn form, Forgot Password form, Respond/Reject message form, Get in touch form.
- In SignIn modal fixed the modal to show the error only in the toast when wrong credentials are entered.
- Now User Info form shows error in the toast not above the input field.
- Now Docs page change code language throughout whole code blocks consistently.

### File changes :
- Mutating from 500 words limit to 100 words 
[‎app/schemas/operator.js](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-44299cebbfbef36d4d49c3a8f061ded97c630d271c98b4b4f6795f7feeee6e2f), [‎app/schemas/request.js](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-22797940cffd0c5e9d21ff1acbe0dde66346327b00aa0960ee912cce11d81f97) - changed schema from accepting 500 to 100 words .
[‎ui/src/utils/Constants.js](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-823ee393f58a1256468c241c46b3473538cc82871298034e5dc043a5a712d758) - changed constants for accepting 100 words.
[‎ui/src/utils/Helpers.js](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-da4abfa5d28f3bbb7d9519020b4916110c6a353a6d6c3f7a068ce8325a8bf72b) - changed validateField function to validate on 100 words instead of 500.
[‎app/__tests__/controllers/operator/respond-messages.js](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-20924227d065b82095838f32dff240c6e72ebe72bbdf2bd6644242298cb819f6) , [‎app/__tests__/controllers/operator/update-requests.js](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-3b94ef1b0058e3993fbd8147df372ad4225539f721ab1e9d0ff851fc87fc15b5) - Backend test to return the error for 100 words instead of 500.

- For using toasts for error and updating loading state to spinner 
[‎ui/src/components/auth/Signin.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-08836673334e3f1f0791724c755ee0d66cddc1a53db88912026d0fffd8b5444a) - removed local error message  inside for and added the button parameter isLoading to show spinner.
[‎ui/src/components/contact/ContactForm.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-6aa3dacaa45b755f45a2d3e6039a44b192777d0cfbc250556c49e5375ad8f4d6) - fix the effect run on getting data or error and updated loading state.
[‎ui/src/components/operator/OperatorDashboard.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-a27eede5a7b5a06f362d0cfc6d690e5ff6dd13e2a854ada62fbe2c1e8ea69f53) - updated loading state as spinner
[‎ui/__tests__/components/auth/Signin.test.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-1b276de55b302b7ad0d18b67abc75b5341183ab9eb006673480b9ace4fb3a9e7) , [‎ui/__tests__/components/contact/ContactForm.test.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-597cba85470c61b5532ded4867d393a465b179ff69e6b75cc6a3337bee79ac60) , [‎ui/__tests__/components/operatordashboard/OperatorDashboard.test.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-3d9022887c87bce9eabbe81599c14ce9a97078314be7477e50bc17e4d6b42ce4) - tests for loading states
- Docs codeblock bug 
[‎ui/src/page/documentation/CodeBlock.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-6784845332233e5118c60b68e24a89f5c2f713d09de6c1adf68e86b8572370b0) , [‎ui/src/page/documentation/Documentation.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-b5d544da872c2d62b739d98b7ce94ff2cd186376f7c09665ad7fbc48be6cd1ca) - moved the select language state to parent component.
[‎ui/__tests__/page/documentation/CodeBlock.test.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-c214c897bd74cb8da2334e5a8e8e4881a6e7d4ef3863a467a31806b8c5b360f0) - codeblock test update.
- User Info form input field validation
[‎ui/src/components/userinfo/UserInfo.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-48ba87b4e6118a6648a8f76e013d2d44ad75a8204445d35342fa281855dc5462) - added userinfo form validation in client side.
[‎ui/__tests__/components/UserInfo.test.jsx](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-d40151559944f1f475e5e4318e473b68d1f51ab4175cea9dc269f654d1196d1f) - test typo mismatch update.
- Operator card styling fix
[‎ui/src/components/operatorcard/OperatorCard.module.css](https://github.com/TeamShiksha/openlogo/pull/817/files#diff-1aeafd762d1e52d34358a008b74425602e08d30da71bd627740be7be7e2615eb) 

## What type of PR is this? (Check all applicable)

- [x] 🐛 Bug Fix
- [x] ✅ Test

## Screenshots (if applicable)
[fix_#185.webm](https://github.com/user-attachments/assets/60b0daf2-a589-42ec-a5ea-f14df02e6bbd)

Screenshot from 2025-08-26 22-58-21
Screenshot from 2025-08-26 22-58-47

## Checklist
- [x] I have performed a self-review of my code  
- [x] I have added tests that prove my fix is effective or that my feature works  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ui/src/components/userinfo/UserInfo.jsx
Comment (theboyofdream) [inline packages/ui/src/components/userinfo/UserInfo.jsx:1]: kindly add proper name validation for username input
For ref use see SignUp component validation of fullname

image

File: packages/ui/__tests__/page/documentation/CodeBlock.test.jsx [hunk 1]
```diff
@@ -2,24 +2,49 @@ import { describe, it, expect, vi } from "vitest";
...
+import { useState } from "react";
+import PropTypes from "prop-types";
 
 const mockCodeExamples = {
   javascript: "console.log('Hello, JavaScript!');",
   python: "print('Hello, Python!')",
   java: "System.out.println('Hello, Java!');",
 };
 
+const Harness = ({ initial = "javascript" }) => {
```
Comment (theboyofdream) [inline packages/ui/__tests__/page/documentation/CodeBlock.test.jsx]: why name Harness

File: packages/ui/__tests__/page/documentation/CodeBlock.test.jsx [hunk 2]
```diff
@@ -46,7 +71,14 @@ describe("CodeBlock component", () => {
   });
 
   it("Renders buttons for all available languages", () => {
-    render(<CodeBlock id="test" codeExamples={mockCodeExamples} />);
+    render(
+      <CodeBlock
```
Comment (theboyofdream) [inline packages/ui/__tests__/page/documentation/CodeBlock.test.jsx]: You declared `Harness` which is MockCodeBlock & here you are using normal CodeBlock.
This will lead to inconsistent test-writing patterns in our repo.
So, just use CodeBlock & remove custom MockCodeBloack
For more refs please take a look into other components test-cases

**Review by theboyofdream — CHANGES_REQUESTED** [review]
Summary of suggested changes:
- fix inconsistency in test-case in `CodeBlock.test.jsx`
- add proper name validation in `UserInfo.jsx`

File: packages/ui/__tests__/page/documentation/CodeBlock.test.jsx (hunk 2 above)
Comment (Aniketvish0) [reply packages/ui/__tests__/page/documentation/CodeBlock.test.jsx]: fixed in the update now using consistent component name

File: packages/ui/src/components/userinfo/UserInfo.jsx
Comment (Aniketvish0) [reply packages/ui/src/components/userinfo/UserInfo.jsx:1]: fixed in the latest commit

**Review by theboyofdream — APPROVED** [review]
PR is big. Kindly, update the PR description - outlining the all changes made along with file / component name

**Comment by Aniketvish0** [comment]
> PR is big. Kindly, update the PR description - outlining the all changes made along with file / component name

Updated the description with detailed explanation
