### PR TITLE
Integrate stats API on frontend, fix: backend JSON response structure

### LINKED ISSUE #696: Integrate analytics API on admin dashboard
### Describe the feature

This integration will fetch the data using stats API and display real statistics on the admin dashboard.

**The GET request fetches the following data-**

Image

### It should be implemented because ? Additional context

The current admin dashboard exhibits dummy data. 

Image

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by AryaDharkar**
## Description
#696 
This PR performs the following functions

1.  Enhance JSON response returned from `http://localhost:5000/api/catalog/stats`
2.  Integrate the API with the frontend `analytics` component on `/admin` dashboard
3. Update the tests for -
- analytics component
-  stats controller
4. Update documentation as per changes

## What type of PR is this? (Check all applicable)

- [x] 🍕 Integration

## Screenshots 

1. Admin dashboard with realtime data
Screenshot 2025-06-02 221055

2. Newly structured JSON response for better frontend mapping
Screenshot 2025-06-02 221150

## Test cases explanation

We use `vi.stubGlobal("fetch", ...)` to mock the browser's `fetch` function and prevent real network requests during testing. It returns a resolved promise with a `.json()` method that also returns a resolved value, simulating how `fetch` normally behaves when calling `await fetch().then(res => res.json())`. This ensures the component receives mock data and renders correctly without relying on the backend / making a network request.

## Checklist
- [x] I have performed a self-review of my code  
- [x] I have commented my code, particularly in hard-to-understand areas  
- [x] I have added tests that prove my fix is effective or that my feature works  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/app/controllers/catalog.js [hunk 1]
```diff
@@ -26,12 +26,25 @@ async function getAnalyticsController(req, res, next) {
 
     return res.status(200).json({
       statusCode: 200,
-      data: {
-        Users: totalUsers,
-        Keys: totalKeys,
-        Requests: totalRequests + totalContactUs,
-        Hits: totalHits,
-      },
+      data: [
```
Comment (aps08) [inline packages/app/controllers/catalog.js:29]: can't we use key value pairs as it is.

```json
users: totalUsers,
keys: totalKeys,
...
```

File: packages/app/utils/mocks.js [hunk 2]
```diff
@@ -134,20 +134,49 @@ const MOCK_KEYS = [
...
 ];
 
-const MOCK_ANALYTICS_DATA_INPUT = {
-  Users: 10,
-  Keys: 20,
-  Requests: 30,
-  ContactUs: 10,
-  Hits: 40,
-};
+const MOCK_ANALYTICS_DATA_INPUT = [
```
Comment (aps08) [inline packages/app/utils/mocks.js:137]: where is this getting used ?

File: packages/ui/__tests__/components/analytics/Analytics.test.jsx [hunk 3]
```diff
@@ -1,18 +1,39 @@
...
+
+  afterEach(() => {
+    vi.restoreAllMocks();
+  });
+
+  it("renders correct number of AnalyticsCard components ", async () => {
     render(<Analytics />);
 
-    const analytics = screen.getByTestId("analytics");
+    const analytics = await screen.getByTestId("analytics");
```
[the remark this answers is not in the document]
Comment (aps08) [reply packages/ui/__tests__/components/analytics/Analytics.test.jsx]: Can you see these suggestion ?

File: packages/ui/src/components/analytics/Analytics.jsx [hunk 4]
```diff
@@ -1,12 +1,30 @@
...
 import styles from "./Analytics.module.css";
+import { useState, useEffect } from "react";
 
 function Analytics() {
+  const [stats, setStats] = useState([]);
+
+  useEffect(() => {
+    const fetchStats = async () => {
+      try {
+        const res = await fetch("http://localhost:5000/api/catalog/stats", {
```
Comment (aps08) [inline packages/ui/src/components/analytics/Analytics.jsx]: is this how we are making API calls in other components ?

File: packages/ui/src/components/analytics/AnalyticsCard.jsx
Comment (aps08) [inline packages/ui/src/components/analytics/AnalyticsCard.jsx:1]: removal all single line comments and form where are you getting `api` variable ?

**Review by aps08 — CHANGES_REQUESTED** [review]
Changes

**Review by aps08 — APPROVED** [review]
