### PR TITLE
Fix Issue #668 - Preserve Form Data on API Error in Sign-Up Process

### LINKED ISSUE #668: Preserve Form Data on API Error in Sign-Up Process
### Describe your issue

On the Sign Up form, if an API error occurs during submission (e.g., invalid email or server error), all user input is cleared.

### Steps to reproduce

1. Navigate to the homepage.
2. Click on Get Started Button in the Navbar
3. Once the dialog opens up click on "Don't have an account?" to go the Sign up form
4. Enter the required fields, but either use an existing email or change the CLIENT_PROXY_URL so you get CORS error.
5. Click on Sign Up Button.
6. Once you receive an error the data entered is also gone.

https://github.com/user-attachments/assets/aaf46e5c-0edd-4f06-be22-89e4c5beadac

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by ShlokMane**
## Summary
Fix Issue 668 - Preserve Form Data on API Error in Sign-Up Process
closes #668 

## Description
Only reinitialize the form once API call response is successful.  

## What type of PR is this? (Check all applicable)
- [x] 🐛 Bug Fix

## Previous State
https://github.com/user-attachments/assets/ffaeca9d-2e5f-4dcf-ac23-018c46b84213

## Current State
https://github.com/user-attachments/assets/f0657130-9d92-496b-aa21-0c166e3d9e52

## Checklist
- [ ] I have performed a self-review of my code  
- [ ] I have commented my code, particularly in hard-to-understand areas  
- [x] I have added tests that prove my fix is effective or that my feature works  
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ui/src/components/auth/Signup.jsx [hunk 1]
```diff
@@ -50,7 +50,6 @@ function SignUp({ toggleForm }) {
 
   const handleSubmit = async (submitEvent) => {
     submitEvent.preventDefault();
-    setFormValues(SIGNUP.initialValues);
```
Comment (shafat730) [inline packages/ui/src/components/auth/Signup.jsx:53]: Fix the test cases for the signup component

**Review by shafat730 — COMMENTED** [review]
Add test coverage screenshot for this component in PR .

File: packages/ui/src/components/auth/Signup.jsx (hunk 1 above)
Comment (ShlokMane) [reply packages/ui/src/components/auth/Signup.jsx:53]: Done

**Review by aps08 — CHANGES_REQUESTED** [review]
add the `toast` which is added recently in the app.

**Comment by ShlokMane** [comment]
> add the `toast` which is added recently in the app.

Is this okay?
https://github.com/user-attachments/assets/1db5d7ef-5be8-4f8e-a25f-0215e0fda6b5

**Comment by aps08** [comment]
> > add the `toast` which is added recently in the app.
> 
> Is this okay? https://github.com/user-attachments/assets/1db5d7ef-5be8-4f8e-a25f-0215e0fda6b5

Yes, add the test cases.

**Review by aps08 — APPROVED** [review]
