### PR TITLE
fix: dashboard loading spinner, dashboard spacing

### LINKED ISSUE #729: [Frontend] Dashboard gap and loader fix
### Gap fix
Correct the gap between the customer dashboard and header.

Image

UI on admin/operator dashboard with dropdown.

Image

### Loader fix
Change the below loader showing "Loading..." to SpinnerLoader

Image

### Why should this enhancement be implemented? Add additional informaiton.

UI improvement and consistency.

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by AryaDharkar**
## Description
#729 

1. Replace dashboard loading with spinner.
2. Fix spacing of dashboard post dropdown merge for customer dashboard.

## What type of PR is this? (Check all applicable)
- [x] 👨‍💻 Code Refactor
- [x] 🔥 UI Improvements

## Screenshots (if applicable)

1. Spinning loader while dashboard render

https://github.com/user-attachments/assets/3919108c-a618-4edd-842c-e6d0ac57a956

2. Dashboard top spacing
Screenshot 2025-06-19 112222
Screenshot 2025-06-19 112202

Screenshot 2025-06-19 112337

## Checklist
- [x] I have performed a self-review of my code  
- [x] I have added tests that prove my fix is effective or that my feature works  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ui/src/page/dashboard/Dashboard.jsx [hunk 1]
```diff
@@ -63,7 +64,14 @@ function Dashboard() {
   };
 
   if (loading) {
-    return <div>loading..</div>;
+    return (
+      <div
+        data-testid="loading-spinner"
+        className={styles["spinner-container"]}
```
Comment (TanishqSingla) [inline packages/ui/src/page/dashboard/Dashboard.jsx:70]: nit: you can name `spinner-container` class as Pascal case that way you can do `styles.SpinnerContainer`

File: packages/ui/src/page/dashboard/Dashboard.module.css [hunk 2]
```diff
@@ -5,11 +5,24 @@
   max-width: 1440px;
 }
 
+.spinner-container {
+  position: fixed;
+  top: 0;
+  left: 0;
+  right: 0;
+  bottom: 0;
```
Comment (TanishqSingla) [inline packages/ui/src/page/dashboard/Dashboard.module.css]: you can use `inset: 0`

File: packages/ui/src/page/dashboard/Dashboard.jsx (hunk 1 above)
Comment (aps08) [reply packages/ui/src/page/dashboard/Dashboard.jsx:70]: no that's not the naming convention we are following in the css if you see the code.

Comment (TanishqSingla) [reply packages/ui/src/page/dashboard/Dashboard.jsx:70]: ok

**Review by aps08 — APPROVED** [review]
