### PR TITLE
Fix: Update Password Integration with its intended api

### LINKED ISSUE #762: Change Password feature is not working properly.
### Describe the issue.
Currently ChangePassword Component which is responsible for updating user from current to new password is not working. It is found that controller, routes and services are available though its been not integrated with its intended API.

### Expected Behavior
1.Validate User Input especially for new password it should not be same as current password.
2.Enable Button only validation conditions are fulfilled.
3.Show a Toast Message based on response, reject if its incorrect otherwise show intended success message and update password.

### Screenshot or recording

https://github.com/user-attachments/assets/7f4447bb-a034-475b-8511-6e13258a73c4

Priority
Medium

Estimate
1 Points

Start Date
24/07/2025

End Date
26/07/2025

### Steps to reproduce

1. Run` pnpm start` on your VS code terminal.
2. Go through `http://localhost:3000/` on your browser.
3. Click `Get started` and signin with your credentials if have on dashboard.
4. Now Go through dashboard you would find update password below.
5. Click on both current and new password field.
6. fill them.
7. click on change password button.

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by printgourav**
## Description
 Closes Issue #762 

 -  Integration of change password component with its intented api.
 -  Ensure toast message are showing success and error.
 -  Added Validation for this.
 -  Added Test Cases for this.

## What type of PR is this? (Check all applicable)

- [x] 🍕 Feature
- [X] 🐛 Bug Fix
- [x] ✅ Test

## Screenshots (if applicable)
https://github.com/user-attachments/assets/730fa977-34ec-4fd2-b72c-4a4e08b40c9e

## Test Result
TestPass

Testresult

## Test Coverage
Coverage Test

## Checklist
- [x] I have performed a self-review of my code  
- [x] I have added tests that prove my fix is effective or that my feature works  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ui/src/components/changepassword/ChangePassword.jsx [hunk 1]
```diff
@@ -36,11 +126,15 @@ function ChangePassword({ isGuest }) {
...
+          onBlur={handleBlur}
           required
+          error={
+            touched[field.name] && errors[field.name] ? errors[field.name] : ""
+          }
         />
       ))}
-      <Button type="submit" variant="primary" disabled={isGuest}>
-        {BUTTON_TEXT.changePasswordLabel}
+      <Button type="submit" variant="primary" disabled={isFormInvalid}>
```
Comment (theboyofdream) [inline packages/ui/src/components/changepassword/ChangePassword.jsx]: 1. Submit Button should be disable for guests. You can add or condition for disabled 
2. Button component have `isLoading` prop. Instead of using  ternary operator just use `isLoading` prop

File: packages/ui/src/utils/Constants.js [hunk 2]
```diff
@@ -211,6 +211,11 @@ export const PASSWORD_VALIDATION_MESSAGES = {
   generalError: "Password is not secure",
 };
 
+export const CHANGE_PASSWORD = {
+  required_password: "Password is required",
+  same_password: "New password cannot be same as current one",
+};
```
Comment (theboyofdream) [inline packages/ui/src/utils/Constants.js:218]: key name should be in camelCase

File: packages/ui/src/utils/Helpers.js [hunk 3]
```diff
@@ -228,7 +228,52 @@ export const validate = (values) => {
     values.companyDescription && values.companyDescription.length < 20,
     "Description should be at least 20 characters"
   );
+  return errors;
+};
+
+export const validateChangePassword = (values) => {
```
Comment (theboyofdream) [inline packages/ui/src/utils/Helpers.js:234]: do we really need this new validate function? can't we just use the `validate` function with little addition?

File: packages/ui/src/hooks/useApi.js [hunk 4]
```diff
@@ -29,10 +29,11 @@ export const useApi = (config) => {
       success = true;
     } catch (err) {
       setIsSuccess(false);
+      setData(err?.response?.data || null);
```
Comment (theboyofdream) [inline packages/ui/src/hooks/useApi.js:32]: why are you setting data on error?

**Review by theboyofdream — CHANGES_REQUESTED** [review]
Missing test-cases
Also fix the copilot suggestions

File: packages/ui/src/utils/Helpers.js (hunk 3 above)
Comment (printgourav) [reply packages/ui/src/utils/Helpers.js:234]: Yes we need here a new validate function. As Existing valdiate function is there & serving validation for field that might seem similar but they arent there serving purpose is different as asked about inclusion into this existing function instead of creating a new function, earlier did so sonar flagged for Refactor down the preexisting function. This Validation function exclusively serve for changePassword only.

File: packages/ui/src/components/changepassword/ChangePassword.jsx (hunk 1 above)
Comment (printgourav) [reply packages/ui/src/components/changepassword/ChangePassword.jsx]: isFormValid is Boolean variable and ensure button would remain disable if either of conditions that are mentioned within it are true isGuest is one them thats been included.

File: packages/ui/src/utils/Constants.js (hunk 2 above)
Comment (printgourav) [reply packages/ui/src/utils/Constants.js:218]: > key name should be in camelCase

sure.

File: packages/ui/src/hooks/useApi.js (hunk 4 above)
Comment (printgourav) [reply packages/ui/src/hooks/useApi.js:32]: setData gets complete response of error as object that consist of messages that are coming from backend can be further setErrorMsg message incase unknown error network error would be shown.

File: packages/ui/src/components/changepassword/ChangePassword.jsx [hunk 5]
```diff
@@ -1,16 +1,72 @@
...
+        [focusedField]: formValues[focusedField],
+      });
+      setErrors({
+        [focusedField]: validationErrors[focusedField] || "",
+      });
+    }, 500);
+    return () => clearTimeout(timeout);
+  }, [focusedField, formValues]);
+
+  useEffect(() => {
```
Comment (theboyofdream) [inline packages/ui/src/components/changepassword/ChangePassword.jsx:55]: this useEffect is bit complex & can be replaced with simpler one also the part can be moved to handle submit func

**Review by theboyofdream — CHANGES_REQUESTED** [review]

**Review by theboyofdream — DISMISSED** [review]

File: packages/ui/__tests__/components/changePassword.test.jsx [hunk 6]
```diff
@@ -0,0 +1,183 @@
...
+    validateChangePassword.mockImplementation(() => ({}));
+  });
+
+  it("renders form fields and button", () => {
+    render(<ChangePassword isGuest={false} />);
+    CHANGE_PASSWORD_FIELDS.forEach((field) => {
+      expect(screen.getByLabelText(field.label)).toBeInTheDocument();
+    });
+    expect(
+      screen.getByRole("button", { name: BUTTON_TEXT.changePasswordLabel })
```
Comment (theboyofdream) [inline packages/ui/__tests__/components/changePassword.test.jsx]: move screen.getbyrole outside of expect

File: packages/ui/__tests__/components/changePassword.test.jsx [hunk 7]
```diff
@@ -0,0 +1,183 @@
...
+      error: toastErrorMock,
+    });
+
+    validateChangePassword.mockImplementation(() => ({}));
+  });
+
+  it("renders form fields and button", () => {
+    render(<ChangePassword isGuest={false} />);
+    CHANGE_PASSWORD_FIELDS.forEach((field) => {
+      expect(screen.getByLabelText(field.label)).toBeInTheDocument();
```
Comment (theboyofdream) [inline packages/ui/__tests__/components/changePassword.test.jsx]: move screen.getByLabelText out of expect you should be using const and then use that const inside expect

File: packages/ui/__tests__/components/changePassword.test.jsx [hunk 8]
```diff
@@ -0,0 +1,183 @@
...
+
+    await waitFor(() => {
+      expect(
+        screen.getByText("Current password is required")
+      ).toBeInTheDocument();
+    });
+  });
+
+  it("disables button when form is invalid or loading", () => {
+    useApi.mockReturnValueOnce({
```
Comment (theboyofdream) [inline packages/ui/__tests__/components/changePassword.test.jsx]: hooks should be declared outside of test-cases

File: packages/ui/__tests__/components/changePassword.test.jsx [hunk 9]
```diff
@@ -0,0 +1,183 @@
...
+      loading: true,
+    });
+
+    render(<ChangePassword isGuest={false} />);
+    const button = screen.getByRole("button");
+    expect(button).toBeDisabled();
+  });
+
+  it("shows success toast on successful response", async () => {
+    makeRequestMock = vi.fn().mockResolvedValue(true);
```
Comment (theboyofdream) [inline packages/ui/__tests__/components/changePassword.test.jsx]: mock func should be declared outside of test-cases

File: packages/ui/__tests__/components/changePassword.test.jsx [hunk 10]
```diff
@@ -0,0 +1,183 @@
...
+    toastSuccessMock = vi.fn();
+
+    useApi.mockReturnValue({
```
Comment (theboyofdream) [inline packages/ui/__tests__/components/changePassword.test.jsx]: hooks should be declared outside of test-cases

File: packages/ui/__tests__/components/changePassword.test.jsx [hunk 11]
```diff
@@ -0,0 +1,183 @@
...
+      makeRequest: makeRequestMock,
+      errorMsg: "",
+      loading: false,
+    });
+
+    useToast.mockReturnValue({
```
Comment (theboyofdream) [inline packages/ui/__tests__/components/changePassword.test.jsx]: hooks should be declared outside of test-cases

File: packages/ui/__tests__/components/changePassword.test.jsx [hunk 12]
```diff
@@ -0,0 +1,183 @@
...
+  it("shows error toast on incorrect password", async () => {
+    let apiState = {
+      makeRequest: vi.fn(),
+      data: null,
+      errorMsg: "",
+      isSuccess: false,
+      loading: false,
+    };
+
+    useApi.mockImplementation(() => apiState);
```
Comment (theboyofdream) [inline packages/ui/__tests__/components/changePassword.test.jsx]: move out mock value declaration outside of test-case

File: packages/ui/__tests__/components/changePassword.test.jsx [hunk 13]
```diff
@@ -0,0 +1,183 @@
...
+      target: { value: "wrongpass" },
+    });
+
+    fireEvent.change(screen.getByLabelText(/new password/i), {
+      target: { value: "newpass123" },
+    });
+
+    validateChangePassword.mockReturnValue({});
+
+    apiState.makeRequest.mockImplementation(async () => {
```
Comment (theboyofdream) [inline packages/ui/__tests__/components/changePassword.test.jsx]: move out mock value declaration outside of test-case

**Review by theboyofdream — CHANGES_REQUESTED** [review]
- for test-case refer `UserInfo.test.jsx` and `Signup.test.jsx` and implement the syntax
- resolve all github copilot issues
- update PR description, demo video
- add screenshot of total test-cases passed
- add screenshot of test coverage of components you wrote or might get affected

**Review by theboyofdream — CHANGES_REQUESTED** [review]
their are some merge conflicts in constant file

**Review by theboyofdream — DISMISSED** [review]

**Comment by theboyofdream** [comment]
change password form inputs should be empty after successful change

File: packages/ui/src/components/changepassword/ChangePassword.jsx [hunk 14]
```diff
@@ -21,10 +65,25 @@ function ChangePassword({ isGuest }) {
 
   const handleSubmit = async (e) => {
     e.preventDefault();
+    const validationErrors = validateChangePassword(formValues);
+    setErrors(validationErrors);
+    if (Object.keys(validationErrors).length > 0) return;
+    const success = await updatePasswordRequest();
```
[the remark this answers is not in the document]
Comment (Aniketvish0) [reply packages/ui/src/components/changepassword/ChangePassword.jsx:72]: This is not fixed yet, why do you marked it resolved. The form should get reset after successful password change.

**Comment by printgourav** [comment]
> change password form inputs should be empty after successful 

Thanks for pointing out @theboyofdream, I have fixed this with latest commit.

**Review by theboyofdream — APPROVED** [review]

**Review by Aniketvish0 — APPROVED** [review]

**Comment by Aniketvish0** [comment]
@theboyofdream can you check and mark your conversations resolved
