### PR TITLE
fix: logo not found in business api

### LINKED ISSUE #784: Logo not found error in Business logo API
### Describe your issue

- The `api/logo` endpoint giving status `404` when quering for a logo that already exists 
- when we try to search the same logo in `api/logo/search` endpoint. we get the image url with permission denied.

### zoom logo query 

Image

### zoom logo search 

Image

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by theboyofdream**
## Description

Closes Issue: #784 

- Fix logo API image fetch by passing object instead of string

Extra
- Updated api-stage-openlogo.fyi link constant file to api-stage.openlogo.fyi
- Updated jsDoc inside app/services --file-> images, subscription.

## What type of PR is this? (Check all applicable)

- [x] 🐛 Bug Fix
- [x] 📄 Documentation Update

### Logo Retrieval API

image

### Logo Search API 

image

All test-cases passed locally

image

## Checklist
- [x] I have performed a self-review of my code 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Aniketvish0 — DISMISSED** [review]

File: packages/app/controllers/logo.js [hunk 1]
```diff
@@ -51,7 +51,9 @@ async function getLogoController(req, res, next) {
       });
     }
 
-    const imageUrl = await imageService.fetchImageByCompanyFree(company);
+    const imageUrl = await imageService.fetchImageByCompanyFree({
```
Comment (TanishqSingla) [inline packages/app/controllers/logo.js]: This function doesn't take object as arguments, why are we passing company_name like that?

**Review by TanishqSingla — CHANGES_REQUESTED** [review]

**Comment by TanishqSingla** [comment]
Also why were tests not changed, this is a complete function signature change. Don't we have adequate testing for this?

File: packages/app/controllers/logo.js (hunk 1 above)
Comment (theboyofdream) [reply packages/app/controllers/logo.js:54]: image

inside function we are using `company.company_name` so function expects an object

also now after you pointed out 
1. i see that function jsdoc is wrong which i will update
2. we are using `default_extension` variable name which is inconsistent so i am thinking of renaming it to `defaultExtension`
3. this func currently used in 2 places - should i use companyName <string> instead of company <Object>

Comment (theboyofdream) [reply packages/app/controllers/logo.js]: > This function doesn't take object as arguments, why are we passing company_name like that?

image

inside function we are using `company.company_name` so function expects an object

also now after you pointed out 
1. i see that function jsdoc is wrong which i will update
2. we are using `default_extension` variable name which is inconsistent so i am thinking of renaming it to `defaultExtension`
3. this func currently used in 2 places - should i use `companyName <string>` instead of `company <Object>`

Comment (TanishqSingla) [reply packages/app/controllers/logo.js]: ok, fix jsdoc then

File: packages/app/services/subscriptions.js [hunk 2]
```diff
@@ -9,15 +9,15 @@ class SubscriptionService {
   /**
    * Gets Subscription by Id.
    * @param {string} subscriptionId - The subscription_id of the user.
-   * @returns {Object} - Subscription Object.
+   * @returns {Promise<Object>} - Subscription Object.
```
Comment (TanishqSingla) [inline packages/app/services/subscriptions.js:12]: nit: remove the type here, the lsp can infer

**Review by TanishqSingla — APPROVED** [review]

**Comment by aps08** [comment]
Will deploy it in the evening. @theboyofdream
