### PR TITLE
[Backend] feat: add validate session route

### LINKED ISSUE #726: [Backend]: Create a route to validate user session
### Describe the feature

This issue is related to #725 

### API contract
GET `/api/auth/validate-session` 
Responses
- `200` Success
```json
{
  statusCode: 200,
  userData: <User data in jwt>
}
```

- `401` Invalid JWT
```json
{
  statusCode: 401
  error: "Unauthorized Access",
  message: "Invalid credentials"
}
```

### It should be implemented because ? Additional context

To allow client to validate the session a new route is needed that will validate the user session cookie.

### Confirmation

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand this documentation issue.

### PR DESCRIPTION
**Pull request by TanishqSingla**
## Description
This PR creates a route for validating session, this route can be used by the client to validate their session. Fixes #726 

## What type of PR is this? (Check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📄 Documentation Update
- [ ] 👨‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🛠️ CI/CD

## Screenshots
`200` - Success
<details><summary>Click to expand</summary>

image

</details>

`400` - Unauthorized access
<details><summary>Click to expand</summary>

image

</details>

Test coverage for auth middleware and controller

<details><summary>Click to expand</summary>

image

</details>

## Checklist
- [x] I have performed a self-review of my code  
- [x] I have commented my code, particularly in hard-to-understand areas  
- [x] I have added tests that prove my fix is effective or that my feature works  
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/app/controllers/auth.js [hunk 1]
```diff
@@ -417,6 +417,10 @@ async function resetPasswordController(req, res, next) {
   }
 }
 
+function validateSessionController(req, res) {
```
Comment (aps08) [inline packages/app/controllers/auth.js:420]: we already had a endpoint for getting user data. Can't we use that ? and what is the information here in the userdata.

**Review by aps08 — CHANGES_REQUESTED** [review]
- missing screenshot or video
- Add endpoints to `ENDPOINTS.md` file at relevant location.
- questions.
- coverage report step didn't ran so provide screenshot.

File: packages/app/controllers/auth.js (hunk 1 above)
Comment (TanishqSingla) [reply packages/app/controllers/auth.js:420]: user data gets additional detail such as subscription details, which are not relevant for creating our cookie.

**Comment by TanishqSingla** [comment]
Test coverage for auth middleware and controller

<details><summary>Click to expand</summary>

image


</details>

**Review by aps08 — APPROVED** [review]
